name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Auth
      run: gh auth login --with-token ${{ secrets.TRIGGER_TOKEN }}
    - name: Trigger publish
      run: gh workflow run main.yml -R clojure/clojure-org-style --ref master
